"""Initial migration

Revision ID: 0ff793897d7d
Revises: 
Create Date: 2026-02-06 18:44:01.728510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff793897d7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('hotspot_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_tracker_id'), 'entity_tracker', ['id'], unique=False)
    op.create_table('funnel_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_metrics_id'), 'funnel_metrics', ['id'], unique=False)
    op.create_table('market_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=50), nullable=False),
    sa.Column('signal_count', sa.Integer(), nullable=True),
    sa.Column('avg_urgency_score', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_trends_id'), 'market_trends', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_table('strategic_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('benchmark_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_benchmarks_id'), 'strategic_benchmarks', ['id'], unique=False)
    op.create_table('technology_radar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tech_name', sa.String(length=100), nullable=False),
    sa.Column('avg_trl_level', sa.Float(), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_radar_id'), 'technology_radar', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('signal_analysis_opportunity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('primary_domain', sa.String(length=50), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('estimated_trl', sa.Integer(), nullable=True),
    sa.Column('companies_mentioned', sa.Text(), nullable=True),
    sa.Column('technologies_mentioned', sa.Text(), nullable=True),
    sa.Column('locations_mentioned', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_analysis_opportunity_id'), 'signal_analysis_opportunity', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['signal_analysis_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('feasibility_studies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('technical_assessment', sa.Text(), nullable=True),
    sa.Column('required_technology_stack', sa.Text(), nullable=True),
    sa.Column('market_analysis', sa.Text(), nullable=True),
    sa.Column('overall_feasibility', sa.String(length=20), nullable=False),
    sa.Column('final_recommendation', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['signal_analysis_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_studies_id'), 'feasibility_studies', ['id'], unique=False)
    op.create_table('knowledge_base_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('feasibility_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('technical_stack', sa.Text(), nullable=True),
    sa.Column('feasibility_score', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['feasibility_id'], ['feasibility_studies.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['signal_analysis_opportunity.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_entries_id'), 'knowledge_base_entries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_entries_id'), table_name='knowledge_base_entries')
    op.drop_table('knowledge_base_entries')
    op.drop_index(op.f('ix_feasibility_studies_id'), table_name='feasibility_studies')
    op.drop_table('feasibility_studies')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_signal_analysis_opportunity_id'), table_name='signal_analysis_opportunity')
    op.drop_table('signal_analysis_opportunity')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_technology_radar_id'), table_name='technology_radar')
    op.drop_table('technology_radar')
    op.drop_index(op.f('ix_strategic_benchmarks_id'), table_name='strategic_benchmarks')
    op.drop_table('strategic_benchmarks')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_market_trends_id'), table_name='market_trends')
    op.drop_table('market_trends')
    op.drop_index(op.f('ix_funnel_metrics_id'), table_name='funnel_metrics')
    op.drop_table('funnel_metrics')
    op.drop_index(op.f('ix_entity_tracker_id'), table_name='entity_tracker')
    op.drop_table('entity_tracker')
    # ### end Alembic commands ###
